name: Node.js CI
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: ['test']
  pull_request:
    branches: ['test']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Install Vercel CLI
        run: yarn --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install Newman
        run: npm i -g newman

      - name: Run tests
        run: newman run contacts.postman_collection.json

      - name: Set Git config
        run: |
          git config --global user.name "Sidney Sousa"
          git config --global user.email "sidney.sousa@ifms.edu.br"

      - name: Merge to main
        run: |
          git add .
          git commit -m "adding dist folder"
          git fetch --unshallow
          git checkout main
          git pull
          git merge --no-ff test -m "Auto-merge test to main branch"
          git push
